### ISSUE TITLE
After fresh install Joomcck menu does not have access set

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#101]
Hello guys, finally I am back. 
So this problem still not solved. 
When I install JoomCCK it does not publish menu item of JoomCCK CP on site. if I check in admin panel menu manager item is published but it does not have set Access so this is why it is not published. 
Can you set to that when installed menu item gets some access level set by default? Because some people may not understand what problem is right away and think that extension does not work.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/da57b424-aa06-425a-b3ab-1a1826e25a34)

**Comment by andiamine** [comment]
thanks, i will check the issue and let you know

**Comment by andiamine** [comment]
what do you think about deleting the code that add this menu item in main menu ?

i prefer user add menu items by himlself.

**Comment by andiamine** [comment]
Maybe we display a warning in joomcck backend admin that inform user to add dashboard link as menu item on new installation ?

**Comment by Giorgi625** [comment]
I do not see problem in removing this feature and letting user create this menu item by themself.

**Comment by andiamine** [comment]
yes it's better to don't auto add menu item to main menu, cuz most will add on other menus. now once installed if menu not found message will display in backend to create a new menu item.
