### ISSUE TITLE
Styling of input and dropdowns in Field add pages

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#103]
So when I add some fields to my type, on some of them in their parameters input fields and dropdown fields look like on screenshot. As you can see "What to show" parameters dropdown has proper style, but all others below it have not. Its not a big deal but it affects design so better to fix it.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/135bf19c-3d00-4f4c-99fe-4d294ccbb22e)

**Comment by Giorgi625** [comment]
Also that radio buttons No and Yes there is "margin right 10px" on No button which I think should be removed.

**Comment by andiamine** [comment]
Still didn't work yet on this field, i will work on it soon, i'm working on one by one :)

**Comment by andiamine** [comment]
Fixed
