### ISSUE TITLE
Category sorting does not work properly

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#104]
On Control panel of Joom CCK where we add new categories and see list of categories it shows by default ID descending, I want to change it and click on different heading(arrows, Title, ID) but instead of changing sorting order it redirects to different page as shown in video below.

https://youtu.be/JYy851UkJ6k

**Comment by Giorgi625** [comment]
Sorting with title and ID on Section manager page works just fine, problem is on Category page only.

**Comment by andiamine** [comment]
Fixed, thanks for reporting the issue
