### ISSUE TITLE
Strange thing happens when I create second section

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#105]
So I have one section already on my test site and want to add another one and see what happens. When I click add button it opens allready existing sections edit page and if I click save and new it creates copy of existing section.
https://youtu.be/whw_VRl308k

**Comment by andiamine** [comment]
this issue doesn't happen in our case, when a click on new i get an empty form.

make sure you are using last php version 8.2 and last Joomla 4.3.2

**Comment by andiamine** [comment]
also try to clear your browser caching.
