### ISSUE TITLE
Problems if Category, Field or maybe also other titles are not latin letters.

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#109]
So I am testing JoomCCK beta on my subdomain. 
I use Georgian letters which use unicode(utf-8) 
While creating Sections, Categories, Types, Fields I do not have problem but when I open section page in frontend and click on publish record to add new record I get this error:
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/0fa653ef-2cc6-4c54-9f32-474a551d8388)

I knew it was problem with Categories as it loaded until Category title, so I decided to create section without category where I allow submit in root of section. 
In this case I have another problem, form is fully shown but field titles which are in Georgian are not shown or show some Notice:
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/dddb8277-3449-4508-ac7b-47e4fbbb1564)

So To be sure that reason of problem is Georgian letters, I created third section, category and type with only latin letters used in names. In this case I did not see any errors, Record Submit form is shown properly but after clicking save button I get this page(but when I go to section page article is submitted and shown in list):
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/d4a5176a-fb64-4fa2-9ac8-7d88599adf10)

**Comment by andiamine** [comment]
thanks for reporting this issue, team will check and update you

**Comment by Giorgi625** [comment]
Any news about this?

**Comment by andiamine** [comment]
Do you still having this issue, can you send us you website access to check the issue ?

please send in our email support.

regards
ANDI

**Comment by Giorgi625** [comment]
I created New website. There I created Section and type with Georgian letters and some fields with Georgian letters and some with   latin. latin letters fields show field label, but Georgian's does not show. 
I also did one thing, as a field name used custom language constant and in language overrides wrote its Georgian value and it showed up so maybe its with database collation of JoomCCK or something like this?
I will send details via email so you can check it.

**Comment by Giorgi625** [comment]
I will also create another section with categories to check if this problem also still exist.

**Comment by Giorgi625** [comment]
can you remind me on which email I should send login details?

**Comment by andiamine** [comment]
you can send us here:
https://www.joomcoder.com/contact-us

**Comment by Giorgi625** [comment]
Sent, I created another section with categories and I do not see there error which I got before, so I guess old website had some other problems which caused this. on a clean install I did not get that error. but not showing Georgian labels still is a problem.

**Comment by andiamine** [comment]
Hi my friend, we didn't receive email from you, please try to send again or open a private ticket support on joomcoder.com

**Comment by Giorgi625** [comment]
Ok I sent private ticket.

**Comment by andiamine** [comment]
issue solved in this commit
https://github.com/JoomCoder-com/JoomCCK/commit/e9c1035e400c218cc82a6b9149b34968c2bae525

**Comment by andiamine** [comment]
new version will be available soon once we finish JoomCCK Extended
