### ISSUE TITLE
default_cindex_joomcck

### ISSUE THREAD

**Issue by mekamak** [JoomCoder-com/JoomCCK#110]
![joomcck1](https://github.com/JoomCoder-com/JoomCCK/assets/12696950/250b7724-6eef-4a2a-9b1a-2b40ab50cafc)

**Comment by LordHelmchen666** [comment]
You need to save your template for default_index in the backend one time. This will create the json file.

**Comment by mekamak** [comment]
Thank you very much.

**Comment by andiamine** [comment]
Thanks @LordHelmchen666
