### ISSUE TITLE
Error when publishing article

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#114]
So I am creating article and when I click save and close I am sent to this error page, article gets anyway published, but why we see this error? It is not able to redirect to Article list as it is set in types submission parameters.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/1fa7806b-e5ec-4320-9792-e8d228f37a2c)

**Comment by Giorgi625** [comment]
Same problem is also if I click save and new button.

**Comment by andiamine** [comment]
Thanks for reporting the issue, same login details as before ?

**Comment by andiamine** [comment]
We are sill working on J5 support, will be available soon.

**Comment by Giorgi625** [comment]
I will send you details in private support. 
Zerevans from Apuhaku sent some amount for support JoomCCK development. Its not much but hope at will help, we will try to donate more later.

**Comment by andiamine** [comment]
Issue solved.
