### ISSUE TITLE
Does not display articles in category,

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#115]
I created Section with multiple categories. I published 3 articles in one category. I see this articles in Section Homepage, but do not see it in category page in which I published this articles.
You can check it here https://gmg.joomla.ge/index.php/products/items/2-products

**Comment by andiamine** [comment]
can you please open private ticket support about it here
https://www.joomcoder.com/my-account/my-tickets-support

**Comment by andiamine** [comment]
Issue happens if you have duplicate aliases on categories.
