### ISSUE TITLE
Can not open "Notification Settings"

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#120]
Version 5.0.0
When i go to ->More -> Notifications and click "Notification Settings" i get the following error
`0 Joomla\CMS\Event\Model\FormEvent::onSetData(): Argument #1 ($value) must be of type object|array, null given, called in /var/www/vhosts/helmut-mueller-online.de/test.helmut-mueller-online.de/libraries/src/Event/AbstractEvent.php on line 225`

**Comment by andiamine** [comment]
Thanks for reporting the issue team will check it and update you soon.

**Comment by andiamine** [comment]
Issue fixed.
