### ISSUE TITLE
On Joomcoders in my downloads still 5.0 version

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#124]
When I download extended version from my downloads page it still downloads pkg_joomcckextended_v5.0_j4.zip file

**Comment by Giorgi625** [comment]
Also its little confusing updating core JoomCCK separately and extended part separately, can't you include core files into extended version as well so people who purchased full version will just update in one step.

**Comment by andiamine** [comment]
Hi my friend, extended version was updated, i did forgot to upload it yesterday.
and you don't have to download it each time, just enter your download id in joomla and will support joomla auto update.

**Comment by Giorgi625** [comment]
where should I write download ID?

**Comment by andiamine** [comment]
read this article:
https://www.joomboost.com/support/documentation/156-joomla-docs/536-add-your-download-key-on-joomla.html

**Comment by Giorgi625** [comment]
I do not see this notification, I have installed JoomCCK from github and then extended from Jooomboost to 5 of my websites but none of them show that I am missing download key. I also have not entered this key in any of them. 
one of them shows download key missing but for JCE Editor, not for JoomCCK. my websites are on J5.

**Comment by Giorgi625** [comment]
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/fdbf1b57-b9f7-444f-b8bf-5665ae1ad5d8)
This is one of the website where I still have not update manually to 5.1.0 version. 
This is same website showing JCE download key missing, but not JoomCCK
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/6073bb1c-84ff-4743-b62f-3075595c35b5)

**Comment by Giorgi625** [comment]
When I go to  Update Sites page in admin and manually check it does not show Download key field in JoomCCK. also if I filter by Download Key supported, missing or exists, I do not see JoomCCK in results.

**Comment by andiamine** [comment]
send me access as superadmin in ticket support to check.

thanks for your patience
