### ISSUE TITLE
Problem with map field still not fixed fully

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#125]
So now we are able to add map field and see its parameters when we are on Type page, but when I go to submit page of article with map field enabled I get this page:
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/69b02068-d2bf-41aa-886b-7414544b2e68)

If I disable map field submit page works fine.

**Comment by andiamine** [comment]
Team is checking right now.

**Comment by Giorgi625** [comment]
Any news?
