### ISSUE TITLE
Can't change order of fields in submit form

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#126]
It was quite a challenge for me in Cobalt as well, but sometimes I was able to get needed result. So When in type fields page in Cpanel I drag fields as I want, it does not remember new ordering and gets back to default. So what is the correct way to make fields in order I want to show up in Submit form?

**Comment by andiamine** [comment]
team will investigate this, i will update you today or tomorrow

**Comment by andiamine** [comment]
always make sure ordering ascending in fields table then order, also we did fix ordering doesn't save, was fixed
