### ISSUE TITLE
Category module template

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#127]
I am sharing category module template which I created. This is how it looks. When you click on Category which has subcategories it opened with animation as seen, but if category does not have sub category it is clickable link and opens page of that category. It is created with Bootstrap 5 Collapse, no other custom coding was used. 
You can improve it and add to JoomCCK package if you want. 
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/caee714d-3038-4c32-af71-2fffa4abd501)
[collapse.zip](https://github.com/JoomCoder-com/JoomCCK/files/13860623/collapse.zip)

**Comment by andiamine** [comment]
I like it, i will check it now

**Comment by andiamine** [comment]
was accepted and added to JoomCCK Core
