### ISSUE TITLE
Some styling problems with template settings modal

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#128]
Here when I scroll all the way to bottom in template setting you can see there are problems with top where tabs have transparent background and are mixed with some settings field and on bottom save buttons background is overlaying over last option field so you can't clearly see it.
This problem is when there is very long page and scroll is activated.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/b6d0f38a-5bc7-49ee-9819-16698c565ee5)

**Comment by andiamine** [comment]
Fixed
