### ISSUE TITLE
Select field styling in submit form

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#129]
Select fields styling in submit form should be fixed. also if you can see below choose file button there is thin line. It is 1px*1px image. I think this should not be seen there.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/139d2d8d-4356-4f0d-a47a-f2ff951f9382)

**Comment by andiamine** [comment]
this is an issue with chosen library custom css, disable "Apply chosen library" param in select field settings, or force height with css
