### ISSUE TITLE
Dashboard problems when access from Section list page

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#130]
So if I am on a specific sections records list page and I click on Sections link on JoomCCK dashboard header, it as normal sends me on Dashboard page where I see list of existing Sections list. I click on add button and instead of showing a form to create new Section it opens edit form for Section from which I have accessed this page. You can see example in video I attached to this post.

https://github.com/JoomCoder-com/JoomCCK/assets/16633699/1b34072e-caaf-4712-ae40-ac5b97584188

**Comment by andiamine** [comment]
Fixed
