### ISSUE TITLE
Error page after creating article

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#132]
I had similar problem before but you fixed it. now it shows different reason which you can check in screenshot below. article is created anyway but I am getting redirected to this page.
To be sure that it is not my templates problem I set default template in JoomCCK and also set Cassiopeia as Joomla template, but problem still exists.

![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/76f30a3a-c0e0-4d7d-9b50-a6a2b5bcfb76)

**Comment by andiamine** [comment]
please open private ticket support at joomcoder about this issue with website login details access as super admin

**Comment by Giorgi625** [comment]
I found out that its because Relation fields. As I mentioned in another post here, it also need to be fixed when Relation fields have non latin labels they are not shown in submit form.
