### ISSUE TITLE
Relation fields have same issue with non latin labels not displaying in submit form

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#133]
I have multiple Relation fields Parent and Child connection between sections and in submit form they are not dispayed because their labels are in Georgian letters. but if I change them to English letters they are displayed. I reported simillar issue before with other fields.

**Comment by andiamine** [comment]
i did check and works fine, please open private ticket support at joomcoder.com

**Comment by Giorgi625** [comment]
I am sorry, It was my fault. I changed some options and it works.
