### ISSUE TITLE
Didn't work drag-and-drop order of fields

### ISSUE THREAD

**Issue by Kraftion** [JoomCoder-com/JoomCCK#135]
Hello
In Groups of fields and fields section doesn't work drag-and-drop order of fields.
Error in JS
![Screenshot from 2024-01-12 14-53-02](https://github.com/JoomCoder-com/JoomCCK/assets/155111283/010b7565-48b6-45f7-89ba-b3e750be7d6c)

**Comment by andiamine** [comment]
Fixed
