### ISSUE TITLE
Url router

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#136]
So I have menu item in joomla with JoomCCK List page type. When in frontend I click on that menuitem it opens this link:
https://apuhaku.fi/en/news/items/10-news.html

I checked and on my old site with Cobalt I have this link: https://apuhaku.com/en/news.html 
I compared and setup section same way as it is in old site but it does not help. what should I do to remove from link extra stuff like "/items/10-news" ?

**Comment by andiamine** [comment]
Fixed, new update is coming soon
