### ISSUE TITLE
Select field width in submit form

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#137]
So select field has option called **Maximum field width (px)** in its parameters and it allows to add number in pixels but what if I would like to give it a 100% instead of fixed pixels? 

Update: I just wrote in its value 100% and it gave full width, but in source code its this way: style="max-width: 100%px" 
I think would be better to remove px from code and user choose write it in pixels or percents. Same goes to multiselect field.
Text field has done it goodin its parameter **size** where you also should point out it is in pixels or percents.

**Comment by andiamine** [comment]
Updated, now can support any units you want
