### ISSUE TITLE
Pagination in Dashboard

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#138]
When I am viewing fields in Type page, pagination is by default on 20 but I have sometimes more then 20 fields in a type, so its annoying to change everytime to show more then 20 fields on a single page. Joomla has in global configs to set default amount of items per page is it possible to use that value for this JoomCCK lists as well in admin? 
I mean not only fields but also list of Sections, Types, Categories.

**Comment by andiamine** [comment]
Done, now you can change pagination from JoomCCK config
