### ISSUE TITLE
Problems with publishing unpublished categories

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#140]
When I am viewing list of categories There is status collumn where I can click on icon and unpublish category, but if I want to publish that category back and I click on X icon, it does not work. So I need to open category settings and find publish option there.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/b9af7c08-2ba5-4a77-a77b-1d21df23e358)

**Comment by andiamine** [comment]
Fixed
