### ISSUE TITLE
JoomCCK page on JoomCoder website

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#141]
I wanted to show a friend link to JoomCCK but I could not find it in main menu dropdown where is list of your extensions, also I went to Extensions page but could not find there either.

**Comment by Giorgi625** [comment]
Yes I know, I just wanted to show info page about extension, so I would not need to explain everything in details to him.

**Comment by andiamine** [comment]
yes we are working on integration with github and our website store so can be downloaded easily from website
