### ISSUE TITLE
Problems with relations fields

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#143]
So I have website about music where I have 3 section: Labels, Groups, and Singgers.
Label is a Entertainment company which owns music **Groups** and **Singers** 
So it has relation with both of them. 
**Group** is music group under **Label** company which has members from section **Singers**. So it also has relation with both other section.
I had this website on Cobalt with J3 where relations fields worked fine. 
Here I tried all 4 options and only two work( Checkbox and Multiselect) but autocomplete and Modal does not show values. 
You can see results from screenshots below, modal option just shows button but do not open modal window, but when I have button in record full view, I mean Add new and Attach exsisting buttons there modal button works fine.

![checkbox-relationfield](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/fdd04159-e40a-49be-a18a-1313b1db9b15)
![modal-relationfield](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/53b8f14c-b96d-4e4e-8d68-77306aa9303e)
![multiselect -relationfield](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/b2ed45f7-984e-4f1f-85dd-d9474c30db7a)
![autocomplete-relationfield](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/8a232e17-8df8-42af-89ff-b044c33e83b9)

I would love to share credentials of website, but it is in Georgian so you may not be able to undestand wheere to search for it.

**Comment by andiamine** [comment]
please open private ticket support with login details access to check it.
