### ISSUE TITLE
Problem with modals

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#144]
Here Save and Close button are over last field in every modal so you can see it
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/ac96b856-5a3a-4aff-9820-b4f290045a27)

I made custom changes in inspect element to see that last field. As you can see there is hidden Cancel buttons field behind that bottom bar of Save and Close buttons in modal, same happens on other modals.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/463505de-910f-4010-9799-f5223e1f01ed)

**Comment by andiamine** [comment]
Fixed
