### ISSUE TITLE
Date field problem in submit form calendar

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#145]
It does not display arrows on sides of January 2024 
![datefield](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/92a79d9c-fd27-4c79-be2f-ae90a8671759)

**Comment by andiamine** [comment]
Fixed

**Comment by andiamine** [comment]
we need to change this library in future and use another one, the one used in JoomCCK is very old.
