### ISSUE TITLE
Filtering by fields in module has problems

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#146]
I published filter module and enabled filtering in various fields. In module I only see label of field but that's all not options to select or chose to filter.
You will be able to see it on same website for which I sent credentials recently about relation fields. 
When you login there you can check right sidebar on this page https://kpop.ge/singers
In source code I see values of this fields but I guess collapse classes should be fixed for BS5. I will take a look maybe I can fix myself

**Comment by Giorgi625** [comment]
I changed to default template from collapse so it now displays values but there are now other problems. I will report them here in details later.

**Comment by Giorgi625** [comment]
First Digits field filter template:
In default template there is this code:
`<div style="margin: 20px;">
	<div id="digitslider<?php echo $this->key;?>"></div>
</div>

<div style="margin: 20px;">
	<div class="float-start form-inline">
		<label class=""><?php echo $this->params->get('params.label_min') ?> </label>

		<div class="<?php if($prep) {echo ' input-prepend';} if($app) {echo ' input-append';}?>">
			<?php if($prep):?>
				<span class="add-on"><?php echo $prep;?></span>
			<?php endif; ?>

			<input autocomplete="off" type="text" style="width:100px" name="filters[<?php echo $this->key;?>][min]" id="input_minmax_min<?php echo $this->id;?>" value="<?php echo $this->value->get('min', $data->min);?>" />

			<?php if($app):?>
				<span class="add-on"><?php echo $app;?></span>
			<?php endif; ?>
		</div>
	</div>

	<div class="float-end form-inline">
		<label class=""><?php echo $this->params->get('params.label_max') ?></label>

		<div class="<?php if($prep) {echo ' input-prepend';} if($app) {echo ' input-append';}?>">
			<?php if($prep):?>
				<span class="add-on"><?php echo $prep;?></span>
			<?php endif; ?>

			<input autocomplete="off" type="text" style="width:100px" name="filters[<?php echo $this->key;?>][max]" id="input_minmax_max<?php echo $this->id;?>" value="<?php echo $this->value->get('max', $data->max);?>" />

			<?php if($app):?>
				<span class="add-on"><?php echo $app;?></span>
			<?php endif; ?>
		</div>
	</div>
</div>`


I changed it to this according to Bootstrap 5 docs:
`<div>
	<div id="digitslider<?php echo $this->key;?>"></div>
</div>
<div class="row">
	<div class="col">
		<label class=""><?php echo $this->params->get('params.label_min') ?> </label>
		<div class="input-group">
			<?php if($prep):?>
				<span class="input-group-text"><?php echo $prep;?></span>
			<?php endif; ?>
			<input type="text" name="filters[<?php echo $this->key;?>][min]" autocomplete="off" type="text" class="form-control" id="input_minmax_min<?php echo $this->id;?>" value="<?php echo $this->value->get('min', $data->min);?>">
			<?php if($app):?>
				<span class="input-group-text"><?php echo $app;?></span>
			<?php endif; ?>
		</div>
	</div>
	<div class="col">
		<label class=""><?php echo $this->params->get('params.label_max') ?></label>
		<div class="input-group">
			<?php if($prep):?>
				<span class="input-group-text"><?php echo $prep;?></span>
			<?php endif; ?>
			<input class="form-control" autocomplete="off" type="text" name="filters[<?php echo $this->key;?>][max]" id="input_minmax_max<?php echo $this->id;?>" value="<?php echo $this->value->get('max', $data->max);?>">
			<?php if($app):?>
				<span class="input-group-text"><?php echo $app;?></span>
			<?php endif; ?>
		</div>	
  </div>
</div>`

and you can see difference on screenshot below:
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/cdc5fefe-9768-44f8-8be1-1c17c19d9260)


But that slider does not work, so JS code should be fixed I guess. I am not good at JS.

**Comment by Giorgi625** [comment]
Date field has big problems in filter. 
1. even if I do not select any values it automatically selects date 01 January 1970 and search's records with this value only.
2. If I have set range as a filter option, it anyway searches for only one date, not a dates which are between my selected range.
3. It also had problems with design which I fixed in this file [grange_date_picker.zip](https://github.com/JoomCoder-com/JoomCCK/files/14042597/grange_date_picker.zip) I do not know if I chose proper way, you can take a look.
Here is example of before after
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/d14f9543-c9db-4a77-874f-8d7a8e633600)

**Comment by Giorgi625** [comment]
This is what I see when I just hit search button in filter module, without selecting any dates
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/e3f97338-cc12-4d1e-8e92-be6f28c20c6b)

**Comment by andiamine** [comment]
thanks for checking this, we are going to look at it tomorrow

**Comment by Giorgi625** [comment]
There is problem with autocomplete in multiselect fields filter as well so I guess it not just with relation fields but in general with autocomplete feature.

**Comment by Giorgi625** [comment]
_2. If I have set range as a filter option, it anyway searches for only one date, not a dates which are between my selected range._

This problem from my previous comments was my mistake, turns out there is option in date and time field, which I do not remember in Cobalt, that lets you choose **Filtration type** where you can select how you like to filter work for this field.

**Comment by Giorgi625** [comment]
I fixed collapse template of filter module, [collapse.zip](https://github.com/JoomCoder-com/JoomCCK/files/14087641/collapse.zip) needed just little styling fix.
 I was not able to test with categories and type, because in my sections I do not have categories and use one type per section. but Users, Tags, and fields seems to work.
here is short video showing how collapse works after fix.
https://github.com/JoomCoder-com/JoomCCK/assets/16633699/18c35a9a-7dc1-4a27-b2a8-a057e844055e

**Comment by Giorgi625** [comment]
Will we get filter template fixed for reported fields? It is already month since I reported them.

**Comment by Giorgi625** [comment]
Hello can you fix this? Filter module is one of the important things. I reported it almost 3 months ago.

**Comment by andiamine** [comment]
team is working on it there is many issues, will be stable next week, today i'm going to publish a new update doesn't include filter module issues

**Comment by andiamine** [comment]
js code of fields in filter will not works good if filter module and section filter both displayed, so i suggest if you use filter module to disable filter in section

**Comment by andiamine** [comment]
All issues reported fixed

**Comment by Giorgi625** [comment]
Are you sure that you fixed all issues? I see that you fixed range for digit fields, but when I filter and skip date field and fill other fields and click on search it again sets by default dates from 1970 year. I do not have articles with compatible dates so result is empty.

**Comment by andiamine** [comment]
okey let me check this issue again

**Comment by andiamine** [comment]
this issue was solved in previous update
