### ISSUE TITLE
New custom pagination amount in Dashboard has problems

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#148]
I set to show 50 items. I go to fields list in Type its set to 50. I open one field to edit. save field and when I see fields list pagination is set to 10 by itself.
Strange thing is that it does not happen always. If I finish editing field soon and save it. It again shows 50. but if I leave Field edit page and return to it after time and then save it jumps to 10 so I will investigate it more to provide more details

**Comment by Giorgi625** [comment]
I  notice now this also on Section list pages, it by default displays 10 records when I have set in template options 20. 
And problem with lists in fields still exist like I set it manually to 50, after some time it jumps to 10 and everytime this way.

**Comment by andiamine** [comment]
pagination issues all fixed.
