### ISSUE TITLE
Users online status

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#150]
So If personalization is disabled from start we do not see option to change Online status of the user. 
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/3c78fedb-a8d1-45d9-b6b6-66e8e45b8cee)

So if someone want to disable showing online status they may not notice that there is this option in Section options, because it is hidden if Personalization is disabled.
Even though I like that you hide some fields depending on value of parent field, but in such cases I think we need different solution. 

For me it is not big deal, but for newbies it maybe struggle if they will not know how to do it.
To disable showing online status of user I just enabled Personalization for a moment, then disabled Online status and then disabled again Personalization.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/f2e7fdb6-42a3-4f7c-b123-2ac8fed2cab8)

**Comment by andiamine** [comment]
Fixed
