### ISSUE TITLE
Rating templates

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#157]
I am sharing bunch of rating templates 
[Rating templates.zip](https://github.com/JoomCoder-com/JoomCCK/files/14098487/Rating.templates.zip)

Anyone can paste content of archive into this location **/components/com_joomcck/views/rating_tmpls** and then select template from Type options.

**Comment by andiamine** [comment]
thanks, team will work on JoomCCK tomorrow to fix reported issues and add some improvements

**Comment by andiamine** [comment]
@Giorgi625 thanks was added, so we can support it.
