### ISSUE TITLE
Should I be seeing this in Updates page on Backend??

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#158]
I see 3 items of JoomCCK on Updates sites page in Backend is it normal?
First does not have option to set Download key, second has but after I enter field gets empty and thats it. In third as you can see there is update key saved and it shows up.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/05aea126-4d2d-4ba4-9ca9-91d394817998)

**Comment by andiamine** [comment]
click on rebuild button on actions toolbar, and wrong update site will be removed automatically.
