### ISSUE TITLE
Styling in Markup template

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#160]
As you can see from the image below in User menu dropdown numbers are shown as buttons. Would not be better to make it as badge like in second image?
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/0ebd9979-bf6f-40a0-9c82-efcf38cfcce3)

![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/ae74617b-bb01-47a6-bf26-8625f905f505)

**Comment by andiamine** [comment]
Fixed
