### ISSUE TITLE
Submit form template

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#162]
So in submit form Horizontal tabs and Fieldset work fine, but Vertical tabs and Sliders does not.
I was able to fix Sliders by replacing default classes with BS5 classes, but with Vertical tabs its little different so I am stuck there. Also even if I was able, I do not really like vertical tabs, so I did not think it is worth my time to try to fix it.
[default_form_custom.zip](https://github.com/JoomCoder-com/JoomCCK/files/14200826/default_form_custom.zip)
I just edited code in php file from line 435 to 449.  Maybe this also can be improved.

**Comment by andiamine** [comment]
Thanks, team is working on it.

**Comment by andiamine** [comment]
We did update submission form structure now we use JLayouts for better reuse and to minimize code duplication
also we added 2 new features:
- add custom js code
- display groups as cards in form
