### ISSUE TITLE
Styling problems in Audit trail tab of Type settings

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#163]
This is how it looks, I would try to fix it, but I do not know where is file located. I think using Bootstrap switches would be more preferable here https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches it would take less space. No need to have everywhere this big radio buttons.
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/4cb01db4-5f98-4271-ac4c-be9cd9f2f2ab)

**Comment by andiamine** [comment]
Issue fixed
