### ISSUE TITLE
Improvement in comment submit form

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#164]
So when we use JoomCCK Comment provider after editor we have 3 columns with Follow, Private and Access options as seen in screenshot below. 
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/81d06b95-9cf8-43f1-aba3-3f73152e7c30)

What I suggest is instead of using **col-md-4** use just **col**, because all 3 columns have same width and if I disable some of them, active columns stay same width but because labels does not fit in that width they have 4 lines in height and on the right there is too much free space(see screenshots below). 
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/572f73ab-6c6f-4432-96e9-8810e6f057e0)

![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/e1a48fe9-cb27-4f3b-a525-bf9419ae582e)

But if we will set to class just **col** it will automatically stretch active column after disabling others as seen in screenshots below
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/279b4092-6e05-4bf6-b0fa-6e4154f0d4bf)

![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/c3bf8733-acbe-4f8c-a763-ad6bd8041ca7)

But here is another problem with html markup, there is too much elements 

```
<div class="controls">
	<div class="form-check form-check-inline">
		<input type="checkbox" name="jform[subscribe]" id="jform_subscribe" class="form-check-input" value="1">
	</div>
	<div id="jform_subscribe-desc" class="">
		<small class="form-text">Alert me if new comments or other important events are happen.</small>
	</div>
</div>
```

This is code for Follow checkbox and label. but Bootstrap 5 code is this:

```
<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" for="flexCheckDefault">Default checkbox</label>
</div>
```

There is no need to use extra div there. and if I remove 4 and 5 lines from first code it this is how it looks, is not it better?
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/058178ba-8835-45b3-a2a1-280904e87c0d)

**Comment by andiamine** [comment]
thanks for your efforts and suggestions, currently your suggestion will not look good on mobile, we did some improvements will be available in next version.

**Comment by Giorgi625** [comment]
you can use this class '**col-12 col-md**' to make full width on mobiles and bigger screens will have different width depending on amount of items.

**Comment by andiamine** [comment]
yes is possible to do that also. but we did minimize the form , check attached screenshot
![comments improved](https://github.com/JoomCoder-com/JoomCCK/assets/6179568/2505a1ef-fd78-4f84-8e26-749c16f8464d)

**Comment by Giorgi625** [comment]
Oh yes its even better, Good job
