### ISSUE TITLE
Any news about Opengraph?

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#169]

**Comment by andiamine** [comment]
Do you suggest to add support for openGraph ?

**Comment by Giorgi625** [comment]
Yes I remember you mentioned that JoomCCK will have built in opengraph support.

**Comment by Giorgi625** [comment]
If not in core at least as field like it was on Cobalt. I think you have created that Opengraph field for Cobalt.

**Comment by andiamine** [comment]
done, will be available in next update.
