### ISSUE TITLE
Section ordering not working

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#172]
Section Primary Order set to "Title Alphabetical" sorts from Z to A.

And when you are editing a sub sections it does not show selected values. it always shows "Inherit"

**Comment by Giorgi625** [comment]
Agreed I set ordering from Older first but it does not work.

**Comment by andiamine** [comment]
Don't forget that Section has 2 ordering params
1 - Primary order param (when user not logged)
2 - Section home order (when user logged)
