### ISSUE TITLE
Field Textarea: Buttons not working 

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#173]
Uncaught ReferenceError: $$ is not defined

https://github.com/JoomCoder-com/JoomCCK/tree/main/components/com_joomcck/fields/textarea/tmpl/input/default.php
Line 124 `var controls = $$('#controls_<?php echo $this->id;?> button');`

**Comment by andiamine** [comment]
Bbcode js issues fixed, thanks
