### ISSUE TITLE
Cant clear notifications

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#174]
When i click "Clear all history" nothing happens. No error shown.
When i click "Mark all read". there is a browser console log entry 
```
XHRPOST
https://helmut-mueller-online.de/hoerbuchtipps.html?task=ajax.mark_notification&tmpl=component
[HTTP/2 500 Internal Server Error 183ms]

```

**Comment by andiamine** [comment]
All issues in notifications center fixed
