### ISSUE TITLE
Cron send notifications error

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#175]
Try to run Cron Job for sending notifications gives an error.
https://helmut-mueller-online.de/index.php?option=com_joomcck&task=cron.sendAlert&secret=xxx
`0 array_key_exists(): Argument #2 ($array) must be of type array, Joomla\Registry\Registry given`

Note secret key masked.

**Comment by andiamine** [comment]
Issue fixed, thanks for reporting this
