### ISSUE TITLE
Search plugin for Joomla not working

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#176]
When i search via Joomla Search it gives me "No results found". Plugin is activated and searchphrase must find results.
![Screenshot_20240227_151929](https://github.com/JoomCoder-com/JoomCCK/assets/43477041/8a2c834b-55f9-4096-8e72-37ffc03e7328)
![Screenshot_20240227_152016](https://github.com/JoomCoder-com/JoomCCK/assets/43477041/74a91bfe-338a-475e-b6f5-3eb12028bcf8)
![Screenshot_20240227_152222](https://github.com/JoomCoder-com/JoomCCK/assets/43477041/c1741b20-f853-4bda-ac2b-5837c812f69e)

**Comment by andiamine** [comment]
All issues with finder fixed, and you will have to reindex finder once we publish the new update.

**Comment by andiamine** [comment]
All issues with finder fixed, and you will have to reindex finder once we publish the new update.
