### ISSUE TITLE
Tooltips invisible (don't show up)

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#178]
There is code in HTML source code that should show tooltips, but they won't if you hover that items.

Example Codes

- Hint when you are not registered to login to post.
 `
<a class="disabled tip-bottom  btn btn-light border btn-sm" rel="tooltip" href="#" data-bs-title="Registrieren oder einloggen um Rezept einzutragen"> <img src="/media/com_joomcck/icons/16/plus.png" align="absmiddle">Neuer Rezept Eintrag </a>
`
- Alphaindex
`<span class="badge bg-warning" onclick="Joomcck.applyFilter('filter_alpha', 'A')" rel="tooltip" data-bs-title="19 Artikel gefunden">A</span>`

- or on Ratingboxes
`<div id="r71bd6f9654929dbfee1b52fc304d9ac9_rateBox"><span rel="tooltip" data-original-title="20%" class=""></span><span rel="tooltip" data-original-title="40%" class=""></span><span rel="tooltip" data-original-title="60%" class=""></span><span rel="tooltip" data-original-title="80%" class=""></span><span rel="tooltip" data-original-title="100%" class=""></span></div>`

**Comment by andiamine** [comment]
Thanks @LordHelmchen666 for your support and reporting this issues , all fixed

**Comment by LordHelmchen666** [comment]
No problem. I think we all want JoomCCK to run smoothly and will be the best CCK.
