### ISSUE TITLE
Can not change article autor

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#179]
You can not change the article autor when creating a new article.

Uncaught TypeError: $ is not a function
206:11 <script>$(document).ready(function() {

Uncaught TypeError: $ is not a function
2097:6      $(document).ready(function(){

Uncaught TypeError: parent.jSelectUser_jform_user_id is not a function
1:20  if (parent) parent.jSelectUser_jform_user_id('120', 'Walfi');

**Comment by andiamine** [comment]
this issue doesn't happen in our case, can you open private ticket on our website and also provide login details to website to check the issue ?

thanks

**Comment by LordHelmchen666** [comment]
I found out it is a template issue with Rockettheme Photon. When i change to Cassiopeia everything is fine. So no JoomCCK bug.

**Comment by LordHelmchen666** [comment]
Finally found the issue. it is in libraries/mint/forms/fields/meuser.php line 71
`$script[] = '$(document).ready(function() {';`
should be
`$script[] = 'jQuery(document).ready(function() {';`

**Comment by andiamine** [comment]
I think it's an issue with Rockettheme doesn't load jquery correctly, but i'm going to change $ to jQuery to support Rockettheme
