### ISSUE TITLE
Tooltips not working on ....

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#184]
There are more tooltips not working.

Bookmark Article
`<img data-original-title="Zu Bookmarks hinzufügen" rel="tooltip" id="bookmark_319" src="https://helmut-mueller-online.de/media/com_joomcck/icons/bookmarks/star/state0.png" alt="Zu Bookmarks hinzufügen">`
data-original-title needs to be data-bs-original-title

Follow Article
`<img data-original-title="Sie folgen diesem Artikel. Klicken um nicht mehr zu folgen." rel="tooltip" id="follow_record_319" src="https://helmut-mueller-online.de/media/com_joomcck/icons/16/follow1.png" alt="Sie folgen diesem Artikel. Klicken um nicht mehr zu folgen.">`
data-original-title needs to be data-bs-original-title

Compare Article
`<img data-original-title="Zur Vergleichsansicht hinzufügen" rel="tooltip" src="https://helmut-mueller-online.de/media/com_joomcck/icons/16/edit-diff.png" alt="Compare">`
data-original-title needs to be data-bs-original-title

Rating Article
`<div id="rddf1f6b7a35c25f0c3022734f8e563b6_rateBox"><span rel="tooltip" data-original-title="Schlecht" class=""></span><span rel="tooltip" data-original-title="Nicht Gut" class=""></span><span rel="tooltip" data-original-title="Befriedigend" class=""></span><span rel="tooltip" data-original-title="Gut" class=""></span><span rel="tooltip" data-original-title="Exzellent" class=""></span></div>`
data-original-title needs to be data-bs-original-title

**Comment by LordHelmchen666** [comment]
I found 9 files with `data-original-title`

1. components/com_joomcck/library/php/helpers/community.php
2. components/com_joomcck/gateways/paypal/tmpl/default.php
3. components/com_joomcck/library/php/helpers/events.php
4. components/com_joomcck/library/js/felixrating.js
5. components/com_joomcck/library/php/helpers/filter.php
6. components/com_joomcck/library/php/helpers/html.php
7. components/com_joomcck/library/js/main.js
8. components/com_joomcck/layouts/search.php
9. components/com_joomcck/library/php/html/tags.php

**Comment by LordHelmchen666** [comment]
There are also 34 files with `data-bs-title`
I think they all needs to be changed to `data-bs-original-title`

**Comment by andiamine** [comment]
thanks for reporting this issue, was updated.
