### ISSUE TITLE
joomcckrelate.php error

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#186]
components/com_joomcck/library/php/fields/joomcckrelate.php line 518
`$file = JPATH_ADMINISTRATOR . '/components/com_joomcck/tables/field.php';`
must be
`$file = JPATH_ROOT. '/components/com_joomcck/tables/field.php';`
because there is no such file in administrator directory.

**Comment by andiamine** [comment]
Fixed, thanks
