### ISSUE TITLE
Filter checkbox error

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#187]
```
0 Cannot access offset of type string on string
  Call Staclk

# | Function | Location
1 | () | JROOT/components/com_joomcck/fields/checkbox/tmpl/filter/checkboxes.php:19
```

**Comment by andiamine** [comment]
we are not able to get this issue we need to check your website, here how looks in our demo
![checkbox_filter](https://github.com/JoomCoder-com/JoomCCK/assets/6179568/1a0db86d-9cf8-4b6d-9c53-bd5e92e5cb77)

**Comment by andiamine** [comment]
Okey, i will close this one.
