### ISSUE TITLE
Problem with dashboard navbar still exist

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#189]
I reported this error long time ago and you wrote that you fixed it and released update. But this error still exist : I mean when I am on page of any section list and I click on **Admin dashboard'**s Section link and click on add button I just opens edit page of a section from where I came to this page so if I make some mistake it overwrites that section parameters, couple time I did not noticed it so I simply created problems for myself. If you go to Admin dashboard menu item and from access Section pages and click add button it works fine.
you can see everything in video below 

https://github.com/JoomCoder-com/JoomCCK/assets/16633699/cab91ba3-978c-4090-9553-bda8e396aba9

**Comment by andiamine** [comment]
send us access as super admin in our email to investigate this issue.

**Comment by andiamine** [comment]
Issue solved

**Comment by andiamine** [comment]
please update your website to last version
