### ISSUE TITLE
JoomCCK comment option has problems

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#193]
When I delete comment it redirects me to error page saying this page does not exist.
Second problem is when I want to edit comment I has half transparent layer on top but there does not appear modal window, so I guess there is still BS2 code from old Cobalt.
Also I do not know what can be reason but I want to add with TinyMCE editor video, in editor until publishing comment I see video preview, but publish comment does not show video it is empty comment. I do not know if it is JoomCCK problem or TinyMCE or Joomla, I disabled iframe blocking in TinyMCE.
problem is again on apuhaku.fi on this page https://apuhaku.fi/fi/item/54.html
comment by hades422 should show video.

**Comment by andiamine** [comment]
thanks for reporting this issue, team will check it and update you.

**Comment by Giorgi625** [comment]
Can I ask about one thing? for example I am using JCE editor in html field in my section. there I need to have many tools to be able to stylize my content differently, but I also want to use JCE editor in comments, cause I do not really like TinyMCE. but in comments I just need few things like fonts styles, lists, add image, video and emoticons. 
JCE Editor has option to setup different profiles. is it possible to do some changes so there will be possibility to set one profile for html field and another for comments?

**Comment by Giorgi625** [comment]
any news?

**Comment by andiamine** [comment]
"Second problem is when I want to edit comment I has half transparent layer on top but there does not appear modal window, so I guess there is still BS2 code from old Cobalt."

Fixed

**Comment by andiamine** [comment]
"When I delete comment it redirects me to error page saying this page does not exist."

Also fixed

**Comment by andiamine** [comment]
> There is also problem in comments. I have problems adding youtube videos. when I add video in editor it shows up but once I submit comment with video, videos can't be seen in comment. I use same editor in articl html field and there video shows up without problem.

which editor are you using ?

**Comment by Giorgi625** [comment]
It happened with both TinyMCE end JCE Editor Pro.

**Comment by andiamine** [comment]
do you use shortcode or editor to embed ?

**Comment by Giorgi625** [comment]
editors media tools

**Comment by andiamine** [comment]
try to edit comment and see if the code of youtube was stripped out (update first to 5.3.2)

**Comment by Giorgi625** [comment]
I added new comment and it again stripped video from comment. its on apuhaku.fi you have access to that website here is article to which I add comments https://apuhaku.fi/fi/item/54.html

**Comment by andiamine** [comment]
try this
For TinyMCE editor:
Plugins > TinyMCE > in set-0 settings turn on "Use Joomla Text Filter"

For JCE editor:
Components > JCE Editor > Global Configuration > turn off "Validate HTML"

**Comment by andiamine** [comment]
also we did found a small issue, will publish a new update after some few hours
