### ISSUE TITLE
File Upload Field is missing ??!!

### ISSUE THREAD

**Issue by mozaffar** [JoomCoder-com/JoomCCK#197]
Hi,
First let me appreciate your time and effort to migrate this valuable component to new Joomla!.

I installed it for a company but unfortunately I couldn't find the field for **file upload**. It has just fields for accessing pre-uploaded files and media. As you remember the Cobalt component had a special field for file upload. I checked the Pro version but unfortunately couldn't find it there too.

Do you have it in Pro version or not? I think this field one of the most important fields of this component

**Comment by andiamine** [comment]
Hi my friend, JoomCCK doesn't have a field called "File Upload", but we do have field called "Uploads".

**Comment by andiamine** [comment]
Found it, will be added in next update.
