### ISSUE TITLE
Mask option in text field

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#199]
Please take a look at mask settings in text field, when I select any of the mask types it does not load input field next to it. I need to apply field and after page refreshes only then I see input field, also styling is off.

**Comment by andiamine** [comment]
mask library is very old, will be replaced with this one:
https://github.com/uNmAnNeR/imaskjs

**Comment by andiamine** [comment]
Done now we use IMaskJS library instead of the old one
