### ISSUE TITLE
Joomla\Filesystem\File::getExt() error while uploading files

### ISSUE THREAD

**Issue by mozaffar** [JoomCoder-com/JoomCCK#200]
On Joomla 4.4.3, when you upload a file using "Uploads" field, it will display "**Joomla\Filesystem\File::getExt()**" error. It seems that you should "Joomla\**CMS**\Filesystem\File::getExt()" instead. I replaced all occurences and it worked.

**Comment by andiamine** [comment]
thanks, will be fixed in next update.

**Comment by andiamine** [comment]
Fixed
