### ISSUE TITLE
Using Byte for Uploads field is a bit strange

### ISSUE THREAD

**Issue by mozaffar** [JoomCoder-com/JoomCCK#201]
In Uploads field the file size is in "Bytes" which is really strange. For example if you want to set the max. file size to **10 MB** you should set **_10000000 !_**. Isn't it better to use **MB** or at least **KB**?

[Screenshot from 2024-04-16 06-27-08](https://github.com/JoomCoder-com/JoomCCK/assets/10375455/4c19c6aa-122e-412c-ac32-05205d67c6c5)

**Comment by mozaffar** [comment]
Hi,
Have you any workaround on this?

**Comment by mozaffar** [comment]
Hi,
Have you any workaround on this?

**Comment by andiamine** [comment]
Improved
