### ISSUE TITLE
Multi-level select field does not show more than 3 levels

### ISSUE THREAD

**Issue by mozaffar** [JoomCoder-com/JoomCCK#206]
Multi-level select field does not show more than 3 levels

**Comment by andiamine** [comment]
i was able to add many levels, let's follow this issue on ticket support at joomcoder.

**Comment by mozaffar** [comment]
> i was able to add many levels, let's follow this issue on ticket support at joomcoder.

Any action on this? I'm waiting

**Comment by mozaffar** [comment]
Please check the ticketing system in your website (https://www.joomcoder.com/). If you are busy to check ticketing system tell me to follow my problem here. As a customer I cannot purchase and then report bug in your ticket system and follow it up here and wait for a long time for your response.

I appreciate your effort to make this component alive again but we are using this component in our company. We understand that there is always bugs in software but as a paid customer, we expect you to be responsible about tickets and bugs. If you think you don't have enough time for it, please tell us clearly to switch to another solution,

**Comment by andiamine** [comment]
team is still working on it please hold on. we are testing your website backup.

**Comment by andiamine** [comment]
the issue solved in version 5.5.0
