### ISSUE TITLE
Documentation is not Complete

### ISSUE THREAD

**Issue by mozaffar** [JoomCoder-com/JoomCCK#207]
The documentation is not accessible. In some cases it is very important. For example when you are dealing with "Select" fields there is an option for loading data from SQL. This feature is very important. You can use Cobalt documentation as the first version. In this case: [http://docs.mintjoomla.com/en/cobalt/sql-source]

**Comment by andiamine** [comment]
we are working on it , setup section is completed, now working on fields section
