### ISSUE TITLE
Drag and drop sorting of articles in section

### ISSUE THREAD

**Issue by Kraftion** [JoomCoder-com/JoomCCK#209]
Hello
Is it possible in the section to make drag and drop sorting of articles?

**Comment by andiamine** [comment]
currently is not possible but you can change articles order from section settings

**Comment by Giorgi625** [comment]
Did you fixed it because articles ordering did not work in section setting, it only works in markup template.

**Comment by andiamine** [comment]
there is no issue, let me explain:

if user logged , joomcck use home section order, if not logged will use section order.

**Comment by andiamine** [comment]
so you need just to change section home order param for logged users.
