### ISSUE TITLE
Problem with navigation in dashboard

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#213]
In Global configurations I have set **Default List Limit** to 30.
but it always drops to 5 in JoomCCK dashboard, even if I manually set it to other number after few minutes it just goes to 5 itself.
you can see example in video.

https://github.com/JoomCoder-com/JoomCCK/assets/16633699/eb669c48-a5a4-445b-8a8a-1ab16f70bf78

**Comment by andiamine** [comment]
Issue solved, and we added a new param that let you change list limit of items only in config
