### ISSUE TITLE
How it is with Translations?

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#215]
I remember you wrote that you plan to make changes about Translations. have you already done this? is it now safe to translate JoomCCK, or should we still wait?

**Comment by andiamine** [comment]
We are working on it incrementaly cuz it's a lot of work.

we are going to remove all fields languages files and move constants to main language file of component to get less files.

**Comment by andiamine** [comment]
You can start translation now, on crowdin platform here link:
https://crowdin.com/project/joomcck
