### ISSUE TITLE
Creating submit links in admin menu

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#219]
This is how it looks when we create submit links in Joomla admin. 
I really struggle with this because I need to write down IDs of all Sections and types I have to add those links properly.
Is not it possible to show instead of inputs for IDs a dropdown select with Section and Type names?
 
![image](https://github.com/JoomCoder-com/JoomCCK/assets/16633699/1516e439-915e-4385-9da5-8e58f737a53d)

**Comment by andiamine** [comment]
will be improved in the feature

**Comment by andiamine** [comment]
Fixed, thanks for your patience.
