### ISSUE TITLE
Responsive videos in Video field.

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#220]
So when we add youtube videos for example they have fixed width. Which does not look good on mobile devices. I had same problem on Cobalt and fixed it with using text field with custom template.
In text field I would submit youtube video ID, and in custom template I had this file which would make linked videos responsive. Can you convert this to be used in Video field? So linked videos become responsive?
[1551821306_ytid.zip](https://github.com/user-attachments/files/15902195/1551821306_ytid.zip)

**Comment by andiamine** [comment]
Fixed, now just change width param in Player Parameters of video field
