### ISSUE TITLE
Alphaindex customization

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#222]
I like to have on all my websites different style of alpha index. before I would simply go to records templates folder and create copy of markup template. Find alpha index code and edit its css class in that file, but now I see that alpha index code is taken from that file and put in separate folder in com_joomcck/layouts/core/markup

How can I edit alpha index so that it will not be overwritten after update?

**Comment by andiamine** [comment]
We will come with a new good solution soon, currently we are trying to remove duplicate codes using Joomla Layouts.

default alpha index will be found here: /layouts/core/markup/alphaIndex.php

the new structure will some this like this

/layouts/apps/your_section_name/markup/alphaIndex.php (where here you can put your custimized alphaIndex for your section

this solution will be implemented in next version

**Comment by andiamine** [comment]
Please check documentation here
https://github.com/JoomCoder-com/JoomCCK/wiki/Customization
