### ISSUE TITLE
User Groups in JoomCCK

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#228]
So this are user groups in Joomla 
![image](https://github.com/user-attachments/assets/e5cdafd1-71d1-4617-aafe-0428b0ef2515)

and this are options which we can select to allow submit records in types.
![noname](https://github.com/user-attachments/assets/85408808-6666-4d39-8df4-fc343eec673c)

I think it will be good if we will have same User Groups in JoomCCK as in Joomla, because there are scenarios when we have two different user groups setup and want to allow one user group to post in Section 1, and second User group post in Section 2. 
if there is not some hidden feature in JoomCCK, then I do not know how we can do it, 
I think its big minus not be able to limit access to publishing articles to one group of users and allowing them to post in another section only.

**Comment by andiamine** [comment]
You can create different access levels, i don't see any issue with that

**Comment by Giorgi625** [comment]
> You can create different access levels, i don't see any issue with that

I do not really get what you mean, how can I create different access levels in JoomCCK ?

**Comment by andiamine** [comment]
i think it can be achievable using Joomla Access Levels.

- you create access level "Students" and attach to it "Students user group"
- you create access level "Teachers" and attach to it "Teachers user group"

No edit section and in "Who can submit secion" choose accuess level Students or Teachers

**Comment by Giorgi625** [comment]
Oh man I did not even knew that Access level have separate page in Joomla admin, I thought user groups have just access levels as options. Now I found it and I see that Access levels can include multiple user groups. 
Thanks for clarification.

**Comment by andiamine** [comment]
yes it's an old joomla feature you should know it
