### ISSUE TITLE
Category image in categories module

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#241]
So in Section setting we have option to set Category index template and there we are able to select show category image or not.
![image](https://github.com/user-attachments/assets/14a76d40-eb73-4528-8240-3dfe0fc0c983)

But we do not have such options in Category module. There we just select template from dropdowns. It will be good to be able to edit template like in other places but not really important. I am ok with as it is

![image](https://github.com/user-attachments/assets/1ead2722-b5f5-46b5-86c8-ec6182178692)

but will be good if you can give us some piece of code which will let us show category image so we can paste it in file and dislpay Category titles and images.

**Comment by andiamine** [comment]
yes but categories module display categories as list why you want to display image of category, is not gonna look good

**Comment by Giorgi625** [comment]
I want to display it as a grid in separate module on homepage.

**Comment by andiamine** [comment]
ah okey you want cards layout ? we can help you as custom work

**Comment by Giorgi625** [comment]
I already created custom module where I just point images and titles to category urls. Thanks
