### ISSUE TITLE
new video player and playlist

### ISSUE THREAD

**Issue by KEZEO** [JoomCoder-com/JoomCCK#245]
hello just came back. 
very interessing, good work for sure
1) can you add an intégration with other video player. i explain why. my users add some videos in a playlist. they want to find their playlist in their profil. is it possible ?
2) idea would be to add rich snippet / micro date for gallery, video, ect
3) cobalt had a glosssay field to improve internal seo, maybe good idea to do that too.
4) more integration will be amazing; it was the main problem with cobalt, plenty of users requested that

you could put your extension on JED, we could do a good vote

thank you

**Comment by andiamine** [comment]
Hi Kezeo i do remember you, welcome back to our community.

"can you add an intégration with other video player. i explain why. my users add some videos in a playlist. they want to find their playlist in their profil. is it possible ?"

yes we will do it in future, currently we are still working on 4 main things and takes time
- Modernize JoomCCK (as you see now last updates make JoomCCK looks better every time)
- Introduce App Mode (and keep Section mode) we are still working on it and takes a lot of time
- Make some features back and stable like Package
- JoomSubscription (Emerald)

"idea would be to add rich snippet / micro date for gallery, video, ect"

- Yes we will add SEO features in free package to get more users and clients, we will add JSON-LD microdota field soon.

"cobalt had a glosssay field to improve internal seo, maybe good idea to do that too."

- already in the free version https://github.com/JoomCoder-com/JoomCCK/tree/main/plugins/content/glossary

"more integration will be amazing; it was the main problem with cobalt, plenty of users requested that"

- We will  but every step takes time and resources

"you could put your extension on JED, we could do a good vote"

yes will be added soon once we finish 4 main tasks

**Comment by Giorgi625** [comment]
> * JoomSubscription (Emerald)

I think this should be number one priority for now, because, current version of JoomCCK is pretty stable with some minor bugs. 
JoomSubscription will help JoomCCK become more useful in different scenarios. so it should help get more new users. 
App mode is great but at this moment I do not think it is urgent.

**Comment by spinelbusiness** [comment]
agree for video player because current version has big jv logo , not too good, after to have the old joombosst blog theme and a forum theme is good. and i agree joomsubscription is important
