### ISSUE TITLE
change video player

### ISSUE THREAD

**Issue by spinelbusiness** [JoomCoder-com/JoomCCK#248]
hello
would be good to change video player.
i can not upload very big video (3 go) (my server allow )
or maybe doidng an integration with JoomVideos
thank you

**Comment by Giorgi625** [comment]
you can set size in video field setting if you are uploading file. I do not think video field has any limitation in upload size if you have set proper number.

**Comment by andiamine** [comment]
Hi Video Player has nothing to do with uploading file size
