### ISSUE TITLE
very amazing plugin

### ISSUE THREAD

**Issue by CMS-CORP** [JoomCoder-com/JoomCCK#250]
hard to find this extension (not in jed) but it is amazing, really amazing.
1) i have a jw player licence, how to use mine for video field  ?
2) https://smartslider3.com/ had powerfull integration with cobalt, do you know if still available ?
thank you

**Comment by andiamine** [comment]
Hi @CMS-CORP thanks for choosing JoomCCK

1 - we are going to replace and use instead one of this
https://plyr.io/
https://videojs.com/
https://www.mediaelementjs.com/

2 - yes there was a lot of integrations with cobalt previously, and we are going to bring them all back to JoomCCK if possible.

**Comment by CMS-CORP** [comment]
> Hi @CMS-CORP thanks for choosing JoomCCK
> 
> 1 - we are going to replace and use instead one of this https://plyr.io/ https://videojs.com/ https://www.mediaelementjs.com/
> 
> 2 - yes there was a lot of integrations with cobalt previously, and we are going to bring them all back to JoomCCK if possible.

thank you , videojs is very good, it has plenty of plugin from community. we just bought a joomcck licence today and we are going to start testing

**Comment by CMS-CORP** [comment]
thank you , videojs is very good, it has plenty of plugin from community. we just bought a joomcck licence today and we are going to start testing
