### ISSUE TITLE
Does Relation fields work for anyone?

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#258]
I added Child and Parent fields to two different types, but I do not see them in submit forms at all.

**Comment by LordHelmchen666** [comment]
Working for me.
![Screenshot 2024-11-25 at 16-50-32 Bearbeiten Hörbuch - Hörbuchtipps – helmut-mueller-online de](https://github.com/user-attachments/assets/f5481247-2955-4efa-8bc9-07147b598c78)
But if i remember correctly. I did have problems with the template "How to choose children * ". Some of them didn't work. Here is my setting
![Screenshot 2024-11-25 at 16-58-45 Joomcck Admin Dashboard](https://github.com/user-attachments/assets/a0444412-03c6-4aaf-a311-99796f5f49d9)

**Comment by LordHelmchen666** [comment]
![Screenshot 2024-11-26 at 15-46-53 Joomcck Admin Dashboard](https://github.com/user-attachments/assets/48e39614-33f5-4fa6-87ef-4ab155be09da)

I guess you could have problems with your Joomla template. Maybe conflicts with your Javascript, Bootstrap or something like that. You should use your browser console to see if there an errors reported.

**Comment by Giorgi625** [comment]
I decided to use popup option to attach parent so it now works, but I faced new problem. I want to hide add new button from article and set to None value for both Add new and attach existing buttons, but Add new button still shows up.
Does this work on your website?

**Comment by andiamine** [comment]
Issue solved of autocomplete on relation fields. thanks for your patience.
