### ISSUE TITLE
Working hours Field

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#29]
This is usefull in Business Directories where are added details about different companies to show their working hours. But if you do not want to create separate field for this, there is option to add feature to text field. Feature which is in url field to add multiple urls using button +
So If Company has same working hours for every day in a week, author will add it in single input of text field, but if it has different time on saturday and does not work on sunday author will click on + button two times so he will have 3 inputs, on for weekdays and two for saturday and sunday. so it will be flexible for any kind of business.

**Comment by andiamine** [comment]
Thanks for suggestions , we will look at it once JoomCCK is stable :)

**Comment by andiamine** [comment]
Accepted and added to todo list
