### ISSUE TITLE
Show fields by specific category

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#35]
I just got new project and I was thinking how to do it. Of course I plan to use JoomCCK for this project but currently I plan to create it via Cobalt CCK, and then when JoomCCK will be ready upgrade to it. 

So I need to create product catalog with multiple categories. items in different categories have some simillar characteristics and some different so instead of creating multiple types currently I have only option to add all fields to one type, but if someone else will need to add products into catalog they may get confused seeing so much fields.

I like how it is done in Joomla core when creating fields, you can assign them to specific categories and they only show up when you select that category while submitting article. 
I thought it would be cool to add this feature to JoomCCK.

Just submitted this now, so I do not forget to suggest it later.

**Comment by andiamine** [comment]
Good feature, accepted.

**Comment by andiamine** [comment]
added todo list:
https://github.com/JoomCoder-com/JoomCCK/projects
