### ISSUE TITLE
'MControler base' not found

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#38]
After I click on save and close button in JoomCCK Configurations page I see this error
![problem after save configuration](https://user-images.githubusercontent.com/16633699/230432856-ccfb6f76-d279-4e7a-b97d-5db1bd7ad8f6.png)

**Comment by andiamine** [comment]
Fixed, new update will be published now.

**Comment by LordHelmchen666** [comment]
No error when i click "Save", but "Save & Close" i get the error 0 Class "MControllerBase" not found 
Version 4.0a2

**Comment by andiamine** [comment]
Shouldn't happen. issue reopened to check it on your website

**Comment by Giorgi625** [comment]
only Save button works, Save and Close and also just Close button throw MControllerBase error

**Comment by andiamine** [comment]
Fixed
