### ISSUE TITLE
Config SEO options shows index.html

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#40]
I think index.html should not be shown as an option for SEO Router?!
![Screenshot_20230407_152318](https://user-images.githubusercontent.com/43477041/230616669-a01d17c2-42cb-4039-bd90-103296ce4017.png)

**Comment by andiamine** [comment]
thanks for reporting the issue , team will check it and update you.

**Comment by andiamine** [comment]
Fixed
