### ISSUE TITLE
open_basedir restriction in effect on Config

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#41]
```
Warning
: is_dir(): open_basedir restriction in effect. File(/components/com_joomcck/library/php/community) is not within the allowed path(s): (/var/www/vhosts/helmut-mueller-online.de/test.helmut-mueller-online.de/:/tmp/) in
/var/www/vhosts/helmut-mueller-online.de/test.helmut-mueller-online.de/libraries/src/Form/Field/FolderlistField.php
on line
190
```

**Comment by LordHelmchen666** [comment]
It is in Backend - Config - General Settings.
![Screenshot_20230410_165130](https://user-images.githubusercontent.com/43477041/230926126-fb5bfa94-0669-4e84-a359-7c659bdd4536.png)
I think this path /components/com_joomcck/library/php/community  should be relative.

**Comment by LordHelmchen666** [comment]
There is a similiar warning when adding New Section.

![Screenshot_20230410_170122](https://user-images.githubusercontent.com/43477041/230928288-8e7fb2c5-1a77-4a80-9fee-09dcf44e20a9.png)

**Comment by andiamine** [comment]
update will be available today or tomorrow.
