### ISSUE TITLE
Can not install over older version

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#42]
when installing over alpha v1 the v2 it shows empty error box and does not update.
![image](https://user-images.githubusercontent.com/16633699/230667044-801a95b2-8be4-42cf-92b2-d5633ff77a20.png)

**Comment by Giorgi625** [comment]
it worked only after I uninstalled v1 and then installed v2

**Comment by andiamine** [comment]
Didn't happen in our case, it's okey if you uninstall
