### ISSUE TITLE
Can not install over older version again

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#43]
I tried to install v3 over v2 but again same problem red empty warning box after intallation. when try to uninstall it uninstalls everything except Package, and says  'Package Uninstall: Missing manifest file.'
So I am forced again to delete whole test site and install again from zero.

**Comment by Giorgi625** [comment]
So I uninstalled everything except package file in extension manager and then I was able to install v3. but anyway this should be fixed and instalable without uninstalling older version.

**Comment by Giorgi625** [comment]
Now I can access frondend control panel and will start testing.

**Comment by andiamine** [comment]
i will test it on your website, cuz doesn't happen in our demo.

**Comment by Giorgi625** [comment]
Sure I will not deactivate that account so you can compare my and your builds anytime if needed.

**Comment by Giorgi625** [comment]
I do not know, you have not release any new versions, so I have not tried yet.

**Comment by andiamine** [comment]
Tested on your website with alpha 4, and works fine, just sometimes your server fails, and i think is due to your server not JoomCCK package.
