### ISSUE TITLE
Some warning on Quick start page

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#44]
Do not know if it is important or not but with reporting enabled to maximum on Quick Start page it shows this message:
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /libraries/vendor/joomla/registry/src/Format/Json.php on line 54

same message is shown on type and section creation form pages

**Comment by andiamine** [comment]
Issue was fixed.
