### ISSUE TITLE
modal buttons in template edit page

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#45]
This is sections list template edit modal. Buttons below Save and Save & Exit, both show message "Template parameters has been saved successfully" but save and exit does not close modal. even that red close button does not close modal, but that X button on top right closes. So what is purspore of this buttons in bottom?
![template edit page](https://user-images.githubusercontent.com/16633699/230984391-b7bc9252-0620-495d-92e2-56f9fe0621c4.png)

**Comment by andiamine** [comment]
thanks for reporting this, i will check and update you.

**Comment by andiamine** [comment]
Fixed
