### ISSUE TITLE
Fields page: Path is not a folder error

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#46]
This is what I get when I go to fields page in type 
![pathnotafolder](https://user-images.githubusercontent.com/16633699/230986160-22486228-d065-4458-b731-6eb3aacaa289.png)

**Comment by Giorgi625** [comment]
and in New field form page it does not show list of fields types, just empty dropdown
![fields](https://user-images.githubusercontent.com/16633699/230986383-35973194-472f-426e-94e3-1a848c8612db.png)

**Comment by Giorgi625** [comment]
Can you tell us which file was responsible for this so we can replace it and continue testing and not wait for update?

**Comment by andiamine** [comment]
Fields folder was missed on new installation, please update to new alpha
