### ISSUE TITLE
**_js_ip_2_country doesn;t exist

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#47]
This error appears when I click on Records link in JoomCCK control panel.
This error was fixed in Cobalt by installing small plugin which was downloaded separately. pkg_cobalt.ip2country.v.8.0

![records](https://user-images.githubusercontent.com/16633699/230990679-4aae27a7-0a96-474b-9ba1-62be4ce9418c.png)

**Comment by andiamine** [comment]
thanks for reporting this, i will check it and update you.
