### ISSUE TITLE
Articles can be viewed only by author

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#48]
https://cck.joomla.ge/test-section/items/1-test-section this is url of the page where I have published 4 test articles which I can see with my admin user, of course access to articles is set Public, but when I access same page via other browser, with guest or registered user it does not show articles.

**Comment by Giorgi625** [comment]
I checked with another admin user who is not author and I can see this articles. So there is some problem with access levels. 
Status of articles is Published, Access is set to Public.

**Comment by andiamine** [comment]
Thanks for helping us on testing , team working on all reported issues.
