### ISSUE TITLE
Import Packs from Cobalt? 

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#50]
Is it possible to import (install) Packs generated with Cobalt? Would be easier to test functions in Alpha Version instead of rebuilding all manually. Or do you have any other idea.

**Comment by andiamine** [comment]
we still didn't test packs feature very well, i suggest to finish testing main features first like fields, types, submissions ... then we do this as the last thing.

**Comment by LordHelmchen666** [comment]
I understand. Thats ok.
