### ISSUE TITLE
It's working. Thank you.

### ISSUE THREAD

**Issue by mekamak** [JoomCoder-com/JoomCCK#51]
joomcck, It's working. Thank you![joomcck](https://user-images.githubusercontent.com/12696950/233779823-c92b5be1-012d-463b-998d-db6cccf227c4.jpg)

**Comment by Giorgi625** [comment]
Wait are Aklama and Soyadnz fields?

**Comment by andiamine** [comment]
Yes these are fields the issue solved, fields folder was missed on new installation.
Please help us testing fields, i still believe there is many issues in fields.

regards,
ANDI
