### ISSUE TITLE
Meta keywords Not needed

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#52]
When creating New record you could enter Meta keywords under Meta Data Tab. I think this is Not needed anymore.

**Comment by andiamine** [comment]
Hi, i think Yandex search engine still use it

**Comment by andiamine** [comment]
Deleted, thanks

**Comment by andiamine** [comment]
Will be deleted once Joomla will do from Joomla articles, currently still used by Joomla.
