### ISSUE TITLE
Upload field problem

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#54]
this problem ocures when I upload file, seems to be same problem as in audio field.
![upload field](https://user-images.githubusercontent.com/16633699/233827095-8bf04888-3df3-4646-ace7-a9dcbdfebf54.png)

**Comment by andiamine** [comment]
Thanks, issue on all fields that use flow library , new update is coming.

**Comment by andiamine** [comment]
Fixed, new update is coming
