### ISSUE TITLE
Status field problem

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#55]
So when I select status field while creating fields, it does not show data of status field on right collumn. if I click apply I go to this page:
![status field](https://user-images.githubusercontent.com/16633699/233829846-22b4df92-3ed2-4d52-b43a-8b92613dad2b.png)

But instead if I click save it saves field but if I go back to field parameters to see values it again goes to page from image above so I am not able to setup field parameters

**Comment by andiamine** [comment]
Fixed !
