### ISSUE TITLE
Uncaught ReferenceError: Class is not defined

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#57]
I see this two Warnings on this page https://cck.joomla.ge/test-section/item/3-test-article-3
Uncaught ReferenceError: Class is not defined
    at AutoGrow.js:23:16
test-section:103 Uncaught TypeError: AutoGrow is not a constructor
    at test-section:103:6

I clicked in AutoGrow,js and it opened me its content and what I did not liked is that Note on line 16
  * NOTE: This script requires mooTools. Download mooTools at mootools.net.

If it is related to JoomCCK then I hope we get rid of Mootools and use something else for this.

**Comment by andiamine** [comment]
Fixed, autogrow.js replaced with another library
