### ISSUE TITLE
Email field

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#58]
This field seems to be working, I am just reporting some styling issues. 
In popup form is narrow and modal window is wide. form is jsut half width of window so it does not look nice. 
![email field](https://user-images.githubusercontent.com/16633699/233838480-9a55b2e8-4f61-4524-8fe9-323ea77c2e4c.png)

In field edit page in cotrol panel parameters under Sending Options are wide so they go out of their container
![email field2](https://user-images.githubusercontent.com/16633699/233838486-1b383238-6922-454f-ad9b-b9978073f48c.png)

If I set Slidedown as a form style you can see what happenes here https://cck.joomla.ge/test-section/item/3-test-article-3 
First click on button opens form but animation is not smooth and second click does not hide form, it tries but form still appears. I had same problem when used Cobalt with BS4 templates so I guess it needs some styling fix in its template.

**Comment by andiamine** [comment]
All fixed, thanks
