### ISSUE TITLE
Design of Multiple select andcheckbox on submit form

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#59]
Design of Multiple select and checkbox fields on submit form needs to be fixed
![multiple and checkbox](https://user-images.githubusercontent.com/16633699/234047125-de0db3b5-95dd-44cc-bd74-7a67eb8f7015.png)

**Comment by andiamine** [comment]
All fixed, thanks also we did add some new features you can change checkbox type from standard to switches or buttons toggle, also display to columns or inline or vertical and many more :)
