### ISSUE TITLE
JoomCCK Cpanel link does not display when installed

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#64]
I installed on another subdomain JoomCCK and it does not display in menu even tho it is published, until you do not go to Joomla admin menu manager and set access level. Than it appears.

**Comment by andiamine** [comment]
can you send us access in our support email to check the issue ?

**Comment by Giorgi625** [comment]
Sent, I just installed there alpha 4. as alpha 5 does not want to install and you can check that menu item is published but does not have permission set and it does not display on front because of this. once you set permission manually it shows up.

**Comment by andiamine** [comment]
i think issue is related to Github package got corrupted in your case.
