### ISSUE TITLE
Error on uninstalling

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#68]
I get this error when I select JoomCCK package file and click uninstall. I wanted this to try install alpha 5 without update, because update did not work as I reported in another thread.
![error-uninstalling](https://user-images.githubusercontent.com/16633699/235350793-76882734-0089-4c31-98a5-a12b12bce25f.png)

**Comment by andiamine** [comment]
thanks for reporting this. team will check it this week

**Comment by Giorgi625** [comment]
Also please do something with alpha 5 I am not still able to help test it because it does not install on my sites. So I have not contributed since its release.

**Comment by Giorgi625** [comment]
@andiamine  any news why I can't update to Alpha 
LordHelmchen666 is left alone testing, I can not help already for almost two weeks.

**Comment by andiamine** [comment]
Hi my friend, i did attach it and sent true your email v4.0.1

**Comment by andiamine** [comment]
Fixed uninstall issue
