### ISSUE TITLE
Field Email empty Popup, Slidedown

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#70]
Email in Popup and Slidedown mode is empty. Only Fixed is shown.
No errors logged in browser or server logs

**Comment by andiamine** [comment]
can you send us access to your website to check this issue cuz doesn't happen in our case ?

please send login details in support@joomcoder.com

**Comment by andiamine** [comment]
i did check your demo site and works fine in it.
