### ISSUE TITLE
Error on clean install

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#73]
I get error on clean install even when I try on Xampp local server and Hostinger shared hosting. Both throw this error
![Can not clean install](https://user-images.githubusercontent.com/16633699/235375836-ca120649-4122-415e-a258-d8098bf5e6d4.png)

**Comment by andiamine** [comment]
Maybe uploaded file in github broken

**Comment by Giorgi625** [comment]
I downloaded two times but both files have same problem so defninitely this is problem of files here. Both times I installed on clean Joomla.

**Comment by andiamine** [comment]
yes files get corrupted when downloaded from github not sure why this happen.
