### ISSUE TITLE
Module - Video: No templates

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#77]
There are no templates in module.
` Failed opening required '/modules/mod_joomcck_video/tmpl/default.php' `
[modules/mod_joomcck_video](https://github.com/JoomCoder-com/JoomCCK/tree/main/modules/mod_joomcck_video) There is no tmpl directory.  :)

**Comment by andiamine** [comment]
thanks for reporting the issue, this module still not yet tested :) , i will test it this week as well other modules

**Comment by andiamine** [comment]
joomcck video module removed cuz not complete, and i don't see why this module was added by sergey
