### ISSUE TITLE
Module - Categories: Layout mootree error

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#78]
Layout mootree should be deleted or changed to another library. 
mootree.js doesn't exist in J4 anymore or i am wrong?

**Comment by Giorgi625** [comment]
@LordHelmchen666 you are right, mootools is removed from Joomla couple years already. 
By the way are you using alpha 5 version? I am not able to install it so I am stuck and can't help with tests. Can you tell me specs of your evnironment where are you testing?

**Comment by andiamine** [comment]
thanks, will be replace with a new library jquery Tree.

**Comment by andiamine** [comment]
Done, mooTree replaced with jsTree
