### ISSUE TITLE
Tools Uploads Cleanup Error

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#85]
0 Undefined constant "DS" 
https://github.com/JoomCoder-com/JoomCCK/blob/817c0d718596eecaea784d7c6fff2188c1ba4e63/components/com_joomcck/library/php/tools/delfiles/exec.php
line 101       ` $to_delete = JPATH_ROOT . DS . $cp->get('general_upload') . DS . $subfolder . DS . $file->fullpath;`

**Comment by andiamine** [comment]
Fixed
