### ISSUE TITLE
Field Gallery issues

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#96]
Only template working is full-galleria.io.php
All others needs updates because of mootools or Bootstrap related errors.

Also i could not add description. When i click on "T" nothing happens. No errors shown.
We should be able to add Title and Description.

**Comment by andiamine** [comment]
All gallery field issues fixed

- all templates based on galleryBox (built with mootools) removed
- bxSlider removed (very old library)
- Galleria removed (very old library)
- popup with rating, commentings ... features will be back once we found a good library for that :)
- Bootstrap carousel now use BS5
