### ISSUE TITLE
Module Tagcloud: custom template two times choosable

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#98]
custom template two times choosable in general settings.
![Screenshot_20230521_155552](https://github.com/JoomCoder-com/JoomCCK/assets/43477041/6953de15-1f83-4ea5-a36c-b69c437cff02)
First one do not work. So it could be deleted.

**Comment by andiamine** [comment]
thanks will be fixed in next update.

**Comment by andiamine** [comment]
Fixed
