### ISSUE TITLE
Module Tagcloud: cat_id wrong

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#99]
When you are not in a category the link is correct. Example you are here
`https://test.helmut-mueller-online.de/index.php?option=com_joomcck&view=records&section_id=1:sektion-titel&Itemid=147`
Link is
`https://test.helmut-mueller-online.de/index.php?option=com_joomcck&task=records.filter&section_id=1&filter_name[0]=filter_tag&filter_val[0]=1&Itemid=147`
That is working as expected. 

But when you are inside a category then the cat_id value is false. Example you are here
`https://test.helmut-mueller-online.de/index.php?option=com_joomcck&view=records&section_id=1:sektion-titel&cat_id=2:1-kategorie&Itemid=147`
Link is
`https://test.helmut-mueller-online.de/index.php?option=com_joomcck&task=records.filter&section_id=1&cat_id=21&filter_name[0]=filter_tag&filter_val[0]=1&Itemid=147`
cat_id should be "2:1-kategorie"

**Comment by andiamine** [comment]
thanks fore reporting the issue will check it and update you.

**Comment by LordHelmchen666** [comment]
Played a little with settings of the Module.
When i set "Section / Category name - Show" the part `&cat_id=21` is deleted from URL and everything is working as expected.
